# Generated by Django 6.1 on 2026-08-22 21:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
