# Generated by Django 6.1 on 2026-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chat_messages_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
