# Generated by Django 6.1 on 2026-09-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-pin', '-created']},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['created']},
        ),
    ]
