# Generated by Django 6.1 on 2026-09-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chat_options_alter_messages_options'),
        ('home', '0002_profile_created_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
            preserve_default=False,
        ),
    ]
