# Generated by Django 6.1 on 2026-09-13 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chat_user'),
        ('home', '0002_profile_created_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokenizer',
            fields=[
                ('tokenizer', models.IntegerField(default=32768)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
