# Generated by Django 6.1 on 2026-09-13 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_tokenizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenizer',
            name='tokenizer',
            field=models.IntegerField(default=32768, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
