# Generated by Django 6.0.8 on 2026-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_created_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
